### ISSUE TITLE
SyntaxError: JSX value should be either an expression or a quoted JSX text (esbuild-xdm)

### ISSUE THREAD

**Issue by Alarid** [kentcdodds/mdx-bundler#151]
- `mdx-bundler` version: 8.0.1
- `node` version: 16.8.0
- `npm` version: 7.21.0

**Relevant code or config**
```js
import path from "path"
import { bundleMDX } from "mdx-bundler"
import { remarkMdxCodeMeta } from "remark-mdx-code-meta"

const LIBRARY_PATH = path.join(__dirname, "..", "app/components/Library")

export function bundle(mdx: string) {
  return bundleMDX({
    source: mdx,
    cwd: LIBRARY_PATH,
    xdmOptions(options, frontmatter) {
      options.remarkPlugins = [
        ...(options.remarkPlugins ?? []),
        // This plugin causes the bundler to fail
        remarkMdxCodeMeta, ]
      return options
    },
  })
}
```

**What you did:** I added the plugin [remark-mdx-code-meta](https://github.com/remcohaszing/remark-mdx-code-meta) to be able to extract some meta of code snippets inside MDX, like "```jsx filename=MyComponent.tsx"

**What happened:**
```txt
[1] Error: Build failed with 1 error:
[1] _mdx_bundler_entry_point-ef7bfb2c-f085-48e9-a062-7c2ab0cdeb81.mdx:0:0: ERROR: [plugin: esbuild-xdm] SyntaxError: JSX value should be either an expression or a quoted JSX text (1:14)
[1]     at Object.pp$4.raise (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn/dist/acorn.js:3460:15)
[1]     at Object.jsx_parseAttributeValue (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn-jsx/index.js:308:14)
[1]     at Object.jsx_parseAttribute (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn-jsx/index.js:344:43)
[1]     at Object.jsx_parseOpeningElementAt (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn-jsx/index.js:356:35)
[1]     at Object.jsx_parseElementAt (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn-jsx/index.js:378:33)
[1]     at Object.jsx_parseElement (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn-jsx/index.js:436:19)
[1]     at Object.parseExprAtom (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn-jsx/index.js:443:21)
[1]     at Object.pp$5.parseExprSubscripts (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn/dist/acorn.js:2627:21)
[1]     at Object.pp$5.parseMaybeUnary (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn/dist/acorn.js:2593:19)
[1]     at Object.pp$5.parseExprOps (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn/dist/acorn.js:2520:21)
[1]     at failureErrorWithLog (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/esbuild/lib/main.js:1557:15)
[1]     at /Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/esbuild/lib/main.js:1215:28
[1]     at runOnEndCallbacks (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/esbuild/lib/main.js:1005:63)
[1]     at buildResponseToResult (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/esbuild/lib/main.js:1213:7)
[1]     at /Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/esbuild/lib/main.js:1322:14
[1]     at /Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/esbuild/lib/main.js:637:9
[1]     at handleIncomingPacket (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/esbuild/lib/main.js:734:9)
[1]     at Socket.readFromStdout (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/esbuild/lib/main.js:604:7)
[1]     at Socket.emit (node:events:394:28)
[1]     at addChunk (node:internal/streams/readable:315:12) {
[1]   errors: [
[1]     {
[1]       detail: [SyntaxError],
[1]       location: [Object],
[1]       notes: [],
[1]       pluginName: 'esbuild-xdm',
[1]       text: 'SyntaxError: JSX value should be either an expression or a quoted JSX text (1:14)\n' +
[1]         '    at Object.pp$4.raise (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn/dist/acorn.js:3460:15)\n' +
[1]         '    at Object.jsx_parseAttributeValue (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn-jsx/index.js:308:14)\n' +
[1]         '    at Object.jsx_parseAttribute (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn-jsx/index.js:344:43)\n' +
[1]         '    at Object.jsx_parseOpeningElementAt (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn-jsx/index.js:356:35)\n' +
[1]         '    at Object.jsx_parseElementAt (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn-jsx/index.js:378:33)\n' +
[1]         '    at Object.jsx_parseElement (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn-jsx/index.js:436:19)\n' +
[1]         '    at Object.parseExprAtom (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn-jsx/index.js:443:21)\n' +
[1]         '    at Object.pp$5.parseExprSubscripts (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn/dist/acorn.js:2627:21)\n' +
[1]         '    at Object.pp$5.parseMaybeUnary (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn/dist/acorn.js:2593:19)\n' +
[1]         '    at Object.pp$5.parseExprOps (/Users/yohann/Documents/Pro/Dev/coding-crew/course-platform/node_modules/acorn/dist/acorn.js:2520:21)'
[1]     }
[1]   ],
[1]   warnings: []
[1] }
```
**Reproduction repository:** https://github.com/Alarid/mdx-code-meta-repro

**Problem description:** as long as the plugin is included in the `xdmOptions`, the esbuild fails with the above error. I also tried to add `options.jsx = true` in the `xdmOptions`, but that doesn't change anything.

Also, **when there is no meta added to the code snippet**, everything works fine. 

**Suggested solution:** To be fair I am unsure whether the issue comes from mdx-bundler or the plugin, but at the same time I can't get it working and I can't find a solution on the web.

**Comment by lexuantien** [comment]
@Alarid I think the problem is you are missing " " tag. Ex: 
```cs filename="App.css" 
// some code
```
