### ISSUE TITLE
Next.Js build fails with `Error: Not supported` on `bundleMDX()` in getStaticProps

### ISSUE THREAD

**Issue by mojitane** [kentcdodds/mdx-bundler#17]
- `mdx-bundler` version: ^3.1.2
- `node` version: v12.16.3
- `npm` version: 7.6.3

Relevant code or config

```tsx
const mdxSource = `
---
title: Example Post
published: 2021-02-13
description: This is some description
---

# Wahoo

import Demo from './demo'

Here's a **neat** demo:
`.trim();

export const getStaticProps = async () => {
  const result = await bundleMDX(mdxSource);

  console.log(result);

  return {
    props: {},
  };
};

```

What you did:

Hey everyone, I tried replacing my old md setup with mdx bundler. For this I generated a new and clean nextjs (10.1.3) project today.
Using `bundleMDX()` I get the unhelpful error `Error: Not supported` when calling it in my `getStaticProps` function during generation. It's mostly a fresh project except tailwind installed and using out of the box typescript.
It has nothing to do with any other step like reading files as it also happens using the demo inline MDX string from the repo README.

Anything I am overlooking here? I saw the thread about esbuild fails but that seems to be a different issue.

Error message:

```bash
Error: Not supported
    at bundleMDX (project_folder_path/node_modules/mdx-bundler/dist/index.js:40:27)
    at getStaticProps (webpack-internal:///./pages/index.tsx:34:78)
    at renderToHTML (project_folder_path/node_modules/next/dist/next-server/server/render.js:28:1743)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async project_folder_path/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async __wrapper (project_folder_path/node_modules/next/dist/lib/coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (project_folder_path/node_modules/next/dist/next-server/server/next-server.js:137:387)
    at async DevServer.renderToHTML (project_folder_path/node_modules/next/dist/next-server/server/next-server.js:138:522)
    at async DevServer.renderToHTML (project_folder_path/node_modules/next/dist/server/next-dev-server.js:35:578)
    at async DevServer.render (project_folder_path/node_modules/next/dist/next-server/server/next-server.js:75:236)
    at async Object.fn (project_folder_path/node_modules/next/dist/next-server/server/next-server.js:59:580)
    at async Router.execute (project_folder_path/node_modules/next/dist/next-server/server/router.js:25:67)
    at async DevServer.run (project_folder_path/node_modules/next/dist/next-server/server/next-server.js:69:1042)
    at async DevServer.handleRequest (project_folder_path/node_modules/next/dist/next-server/server/next-server.js:34:504)
```

Maybe its something easy I am just not seeing right now. I am thankful for any pointers :)

**Comment by kentcdodds** [comment]
That line in our dynamic import of some native ESM modules (that's the only way to import native ESM from CJS modules). I'm not sure why you're getting that on Node 12 though because that version of nose supports native ESM. Could you try upgrading your version of node though and see if that fixes it?

**Comment by mojitane** [comment]
Thank you, that fixed it. As usual, it is the simple things.
I updated to v15.13.0. Maybe it was some strange issue with my specific version.

**Comment by city17** [comment]
I've also had this issue, and upgrading from Node V12 solved it.
