### ISSUE TITLE
Possible change in documentation for Image Bundling

### ISSUE THREAD

**Issue by ninest** [kentcdodds/mdx-bundler#52]
- `mdx-bundler` version: 4.0.0
- `node` version: 14.16.1
- `yarn` version: 1.22.10

## Relevant code

```js
const result = await bundleMDX(markdownSource, {
  cwd: path.join(process.cwd(), "/posts"),
  esbuildOptions: (options) => {
    options.outdir = path.join(process.cwd(), "/public/generated");
    options.loader = {
      ...options.loader,
      ".png": "file",
    };

    options.publicPath = "/generated/";

    options.write = true;

    return options;
  },
});
```

## What happened:

I followed the bundling images guide in the documentation. See my `bundleMDX` function above. All my images will be bundled into the `notouch/` directory under `public/`.

When you build with this config, you **_might_** get these errors:

<details>

<summary>Errors</summary>

### (1)
```ts
> Build error occurred
Error: Export encountered errors on following paths:
        /
    at /.../node_modules/next/dist/export/index.js:31:1106
    at async Span.traceAsyncFn (/.../node_modules/next/dist/telemetry/trace/trace.js:6:584)
    at async /.../node_modules/next/dist/build/index.js:43:49
    at async Span.traceAsyncFn (/.../node_modules/next/dist/telemetry/trace/trace.js:6:584)
    at async /.../node_modules/next/dist/build/index.js:25:1475
    at async Span.traceAsyncFn (/.../node_modules/next/dist/telemetry/trace/trace.js:6:584)
```

### (2)
```ts
Error: ENOENT: no such file or directory, unlink '/.../public/generatedimages/_mdx_bundler_entry_point.js'
```

### (3)

```ts
ReferenceError: Component is not defined
    at eval (eval at getMDXComponent (/blog/node_modules/mdx-bundler/dist/client.js:34:50), <anonymous>:3:2)
    at getMDXComponent (/blog/node_modules/mdx-bundler/dist/client.js:35:10)
    at Page (/blog/.next/server/pages/[code]/[slug].js:4044:55)
    at d (/blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/blog/node_modules/next/dist/next-server/server/render.js:54:854)
    at Function.getInitialProps (/blog/.next/server/pages/_document.js:721:19)
```

</details>

I got them around 50% of the times I ran `yarn build`

## Reproduction repository:

https://github.com/ninest/next-mdx-bundler-images-bundling-issue

The important file is `mdx.js` at https://github.com/ninest/next-mdx-bundler-images-bundling-issue/blob/main/lib/mdx.js#L42

(None of the blog mdx files have images, but the error still occurs)

A few things to note:

When I use `remark-mdx-images`, I get the error:

<details>

<summary>Error with remark-mdx-images</summary>

```ts
Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:863:33: error: [plugin: esbuild-xdm] Cannot read property 'start' of undefined
    at failureErrorWithLog (blog/node_modules/esbuild/lib/main.js:1443:15)
    at blog/node_modules/esbuild/lib/main.js:1125:28
    at runOnEndCallbacks (blog/node_modules/esbuild/lib/main.js:915:63)
    at buildResponseToResult (blog/node_modules/esbuild/lib/main.js:1123:7)
    at blog/node_modules/esbuild/lib/main.js:1230:14
    at blog/node_modules/esbuild/lib/main.js:606:9
    at handleIncomingPacket (blog/node_modules/esbuild/lib/main.js:703:9)
    at Socket.readFromStdout (blog/node_modules/esbuild/lib/main.js:573:7)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) {
  errors: [
    {
      detail: TypeError: Cannot read property 'start' of undefined
          at onload (file://blog/node_modules/xdm/lib/integration/esbuild.js:87:32)
          at callback (blog/node_modules/esbuild/lib/main.js:863:34)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:93:5)
          at async handleRequest (blog/node_modules/esbuild/lib/main.js:649:30),
      location: [Object],
      notes: [Array],
      pluginName: 'esbuild-xdm',
      text: "Cannot read property 'start' of undefined"
    }
  ],
  warnings: []
}
 > node_modules/esbuild/lib/main.js:863:33: error: [plugin: esbuild-xdm] Cannot read property 'start' of undefined
    863 │               let result = await callback2({
        ╵                                  ^
    at onload (file://blog/node_modules/xdm/lib/integration/esbuild.js:87:32)
    at callback (blog/node_modules/esbuild/lib/main.js:863:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async handleRequest (blog/node_modules/esbuild/lib/main.js:649:30)

   node_modules/esbuild/lib/main.js:733:22: note: This error came from the "onLoad" callback registered here
    733 │         let promise = setup({
        ╵                       ^
    at setup (file://blog/node_modules/xdm/lib/integration/esbuild.js:35:11)
    at handlePlugins (blog/node_modules/esbuild/lib/main.js:733:23)
    at Object.buildOrServe (blog/node_modules/esbuild/lib/main.js:1018:7)
    at blog/node_modules/esbuild/lib/main.js:1742:17
    at new Promise (<anonymous>)
    at Object.build (blog/node_modules/esbuild/lib/main.js:1741:14)
    at Object.build (blog/node_modules/esbuild/lib/main.js:1617:51)
    at bundleMDX (blog/node_modules/mdx-bundler/dist/index.js:192:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getMDX (webpack-internal:///./lib/mdx.js:33:18)
    at async getStaticProps (webpack-internal:///./pages/blog/[slug].js:86:7)
    at async renderToHTML (blog/node_modules/next/dist/next-server/server/render.js:28:1780)
    at async blog/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async __wrapper (blog/node_modules/next/dist/lib/coalesced-function.js:1:330)

Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:863:33: error: [plugin: esbuild-xdm] Cannot read property 'start' of undefined
    at failureErrorWithLog (blog/node_modules/esbuild/lib/main.js:1443:15)
    at blog/node_modules/esbuild/lib/main.js:1125:28
    at runOnEndCallbacks (blog/node_modules/esbuild/lib/main.js:915:63)
    at buildResponseToResult (blog/node_modules/esbuild/lib/main.js:1123:7)
    at blog/node_modules/esbuild/lib/main.js:1230:14
    at blog/node_modules/esbuild/lib/main.js:606:9
    at handleIncomingPacket (blog/node_modules/esbuild/lib/main.js:703:9)
    at Socket.readFromStdout (blog/node_modules/esbuild/lib/main.js:573:7)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) {
  errors: [
    {
      detail: TypeError: Cannot read property 'start' of undefined
          at onload (file://blog/node_modules/xdm/lib/integration/esbuild.js:87:32)
          at callback (blog/node_modules/esbuild/lib/main.js:863:34)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:93:5)
          at async handleRequest (blog/node_modules/esbuild/lib/main.js:649:30),
      location: [Object],
      notes: [Array],
      pluginName: 'esbuild-xdm',
      text: "Cannot read property 'start' of undefined"
    }
  ],
  warnings: []
}
```

</details>

But everything seems to work fine without the remark plugin. Am I doing something incorrectly? Is it something to do with the first argument of `xdmOptions` being `vfile`? When `options` is the second argument, I'm getting the error `TypeError: Cannot read property 'rehypePlugins' of undefined`. (I'm following [this section](https://github.com/kentcdodds/mdx-bundler#xdmoptions))

## Solution:

Use a custom path for each mdx file. I've already made the change at https://github.com/ninest/next-mdx-bundler-images-bundling-issue/blob/main/lib/mdx.js#L42

In `esbuildOptions`, change

```ts
options.outdir = path.join(process.cwd(), `/public/generated`);
...
options.publicPath = "/generated/";
```

to

```ts
options.outdir = path.join(process.cwd(), `/public/generated`, filepath);
...
options.publicPath = filepath;
```

I am not sure why this fixes it, but I believe the explanation is 

> This prevents images from later builds overwriting earlier ones. You have to remember that each call to bundleMDX is isolated so esbuild can't tell if the image it wants to overwrite is from an another build or from the last time your site was built.

https://www.arcath.net/2021/04/images-with-mdx-bundler

Should the documentation be changed to show that the images for each mdx file should be at a custom path? I spent quite a while figuring this out since the error messages (shown under the What happened heading) weren't very clear

**Comment by Arcath** [comment]
@ninest Each time you call `bundleMDX` a new _build pipeline_ is created which has no knowledge of what other mdx files have done to the output dir.

Looks like with putting them all in the same directory the process of reading in and deleting the bundle is getting clobbered by async. It _should_ work if you ran everything syncronously but that would ruin the performance of any site builder.

I'll look at the documentation as it probabbly should warn people about this effect.
