### ISSUE TITLE
TypeError: Failed to resolve module specifier 'xdm/esbuild.js'

### ISSUE THREAD

**Issue by dance2die** [kentcdodds/mdx-bundler#92]
- `mdx-bundler` version: 6.0.1
- `node` version: 14.16.0
- `npm` version: 7.17.0
- `next.js` version: 11.1.2

### Code using `bundleMDX`

```js
import { bundleMDX } from 'mdx-bundler';
import remarkOembed from 'remark-oembed';

const mdxSource = `
Following text should be processd

https://twitter.com/BrendanEich/status/1151317825908166656
`;

const mdxOptions = {
  xdmOptions(options) {
    options.format = 'mdx';
    options.remarkPlugins = [remarkOembed];
    return options;
  },
  esbuildOptions(options) {
    options.minify = false;

    return options;
  }
};

const getBlogData = async () => {
  const mdxData = await bundleMDX(mdxSource.trim(), mdxOptions);
  console.log({ mdxData });

  return { mdxData };
};

export default getBlogData;
```

### Next.js index.js page

```js
import Head from 'next/head';
import React from 'react';

import getBlogData from '../utils/getBlogData';

import styles from '../styles/Home.module.css';

export async function getStaticProps(context) {
  const {
    mdxData: { code, frontmatter }
  } = await getBlogData(context);

  return {
    props: { code, frontmatter }
  };
}

export default function Home({ code, frontmatter }) {
  React.useEffect(() => {
    console.log({ code, frontmatter });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{frontmatter.title}</h1>

        <p className={styles.description}>tags: {frontmatter.tags}</p>
      </main>
    </div>
  );
}

```

**What you did**: Tried to update Webpack config shown here: https://github.com/kentcdodds/mdx-bundler/issues/18#issuecomment-818262064

**What happened:**

```bash
error - TypeError: Failed to resolve module specifier 'xdm/esbuild.js'
    at bundleMDX (/home/projects/nextjs-mgbxuz/node_modules/mdx-bundler/dist/index.js:67:22)
    at getBlogData (webpack-internal:///./utils/getBlogData.js:31:79)
    at getStaticProps (webpack-internal:///./pages/index.js:27:72)
    at Object.renderToHTML (/home/projects/nextjs-mgbxuz/node_modules/next/dist/server/render.js:329:30)
    at async doRender (/home/projects/nextjs-mgbxuz/node_modules/next/dist/server/next-server.js:1144:38)
    at async eval (/home/projects/nextjs-mgbxuz/node_modules/next/dist/server/next-server.js:1236:28)
    at async eval (/home/projects/nextjs-mgbxuz/node_modules/next/dist/server/response-cache.js:64:36) {
  page: '/'
}
```

**Reproduction repository:**

Stackblitz to reproduce the error: https://stackblitz.com/edit/nextjs-mgbxuz?file=pages%2Findex.js

**Problem description:**

Calling `bundleMDX` in Next.js page causes the error for missing 'xdm/esbuild.js' ( as shown in the error message above).

My main goal's to convert the twitter link in MDX file into OEmbed HTML (with `remark-oembed` plugin shown in the first code snippet above).

**Comment by kentcdodds** [comment]
I'm not sure what the issue is with next, but I thought I'd mention that you may want to look into switching `remark-oembed` with [`@remark-embedder/transformer-oembed`](https://github.com/remark-embedder/transformer-oembed) :) It has a much more powerful API :)

Maybe someone else knows what the Next.js issue is.

**Comment by dance2die** [comment]
> you may want to look into switching `remark-oembed` with [`@remark-embedder/transformer-oembed`](https://github.com/remark-embedder/transformer-oembed) :) It has a much more powerful API :)

I like the library. TY for the link and working on`@remark-embedder`.

```js
const mdxOptions = {
  xdmOptions(options) {
    options.format = "mdx";
    options.remarkPlugins = [
      remarkFrontmatter,
      remarkEmbedder, 
      {
        transformers: [oembedTransformer],
      },
    ];
    return options;
  },

};
```

**Comment by kentcdodds** [comment]
You need to use `@remark-embedder/core`

**Comment by dance2die** [comment]
Got it. I had to pass the transformers by passing `remarkEmbedder` in an array.

```js
const mdxOptions = {
  xdmOptions(options) {
    options.format = "mdx";
    options.remarkPlugins = [
      remarkFrontmatter,
      [
        remarkEmbedder,
        {
          transformers: [oembedTransformer],
        },
      ],
    ];
    return options;
  }
};
```

**Comment by dance2die** [comment]
Leaving it aside, the issue seems to be on StackBlitz only (as I was testing there first) not on my local machine.

Closing the issue.
